### ISSUE TITLE
AHN caching does not seem to be working?

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#149]
A repeated run of the following function gives me the log message below:
```python
ahn_ds = nlmod.read.ahn.get_ahn(ds, cachedir=ds.cachedir, cachename="ahn")
```
Log:
```
INFO:nlmod.cache:coordinate x has different values in cached dataset, not using cache
```

I should be seeing a message that AHN is loaded from cache.

**Comment by OnnoEbbens** [comment]
The `get_ahn` function calls the `nlmod.dims.resample.structured_da_to_ds` function. In this function the `da.rio.reproject_match(ds, resampling, nodata=nodata)` function is called which will add 3 attributes to x and y dataarrays:
long_name : x coordinate of projection
standard_name : projection_x_coordinate
units : metre

For the cache we check if the cached dataset (ahn_ds) has the same coordinates and attributes as the given dataset (ds). This check fails because of the new attributes. We decided to check coordinate attributes because some attributes of the time dimension are essential model parameters so should be checked.

The `structured_da_to_ds` already has some logic to remove coordinates added by the `rio.reproject_match` function. I will add some code to remove these attributes of the coordinates as well.

**Comment by OnnoEbbens** [comment]
It turned out to be a lot more complex with coordinates that are added and modified by different functions. With the help of @dbrakenhoff we fixed it but then I referenced the wrong issue number (#150 instead of #149) and everything became even more complex. However I think this issue can be closed.
