### ISSUE TITLE
Extrapolate_regis become part of get_combined_layer_models

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#63]
https://github.com/ArtesiaWater/nlmod/blob/4431929bfa46f49a747805841734fe5ff813787b/nlmod/read/regis.py#L419

Should we make extrapolate_regis part of get_combined_layer_models? And add a keyword argument to optionally turn it off? 

It sounds like a sane default to have it part of get_combined_layer_model and makes it so that users have to remember one line less.

Thanks!

**Comment by OnnoEbbens** [comment]
Yes, we should also add a test and/or example for `extrapolate_regis`.

**Comment by rubencalje** [comment]
regis.extrapolate_regis is renamed to regis.extrapolate_ds (and is faster), and it is called by the method regis.to_model_ds (since Pull Request #61) . This method is called after get_combined_layer_models. In regis.to_model_ds there is a optional parameter 'extrapolate', which does wat @bdestombe wants I think.

So in get_combined_layer_model you get the raw layer-data. They you call to_model_ds, to generate a valid model_ds, with nan's filled and required variables (idomain for example) added.
