### ISSUE TITLE
Info missing: opp_water

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#67]
https://github.com/ArtesiaWater/nlmod/blob/ce8479333b580652150e32f006fbb5823f7944ea/nlmod/read/rws.py#L62

Requires this file to exist: 
```fname = os.path.join(nlmod.NLMOD_DATADIR, "opp_water.shp")```

The shape file also requires several attributes to exist and have reasonal values. Can we get these directly from "basis data"?

**Comment by dbrakenhoff** [comment]
This is an intermediate file that is created using scripts from the [UGW: surface water code](https://github.com/ArtesiaWater/UGW). The code there does attempt to build this intermediate file directly from online source data (but some offline data was still required). This was done for one region (Utrecht) in the Netherlands, with 7 water boards. Unfortunately there is no complete national standard for surface water (yet?), so there was custom code required for the online data for each water board. This might change in the future if we get a functional national database.

So for now we just want to support parsing shapefiles that contain stage info, bottom depths, bed resistance and areas, and creating that file is the users own responsibility. In the future, if we have methods that apply to the Netherlands as a whole we can include those preprocessing steps to create those shapefiles. 

Perhaps we should remove this hard-coded reference to this shapefile and just define its structure.

**Comment by OnnoEbbens** [comment]
There are two different functions for adding surface water which makes things confusing:
1. In `nlmod.read.rws` you can use `get_gdf_surface_water` which uses a shapefile from the data directory. This is a shapefile with all the big surface water bodies in the Netherlands (Noordzee, IJsselmeer, Markermeer). This is the one Bas mentions
2. In `nlmod.mfpackages.surface_water` there are functions to generate a river package from any geodataframe. Typically from river reaches. This is the one Davíd mentions

In the examples the 1st function is used to create a general head boundary for big surface water bodies. You can **not** use the geodataframe from the 1st function to create a river or drain package with the 2nd function.

Now back to the error. The `get_gdf_surface_water` is looking in the nlmod.NLMOD_DATADIR for the shapefile with big surface water bodies. If you installation of nlmod refers to the cloned git repository this is fine because the NLMOD_DATADIR points to the right location. If you've pip installed nlmod there is no data directory on your computer so it fails. I thought I fixed this in setup.py by including the data directory during installation with these lines:

    package_data={"nlmod": ["data/*"]},
    include_package_data=True,

But now I see that this was not fixed at all. I think the solution is to put the data directory inside the nlmod directory. The only annoying thing is that testing is hard because you need to know the results of a `pip install`.
