### ISSUE TITLE
rename methods in mfpackages submodule

### ISSUE THREAD

**Issue by dbrakenhoff** [ArtesiaWater/nlmod#71]
I think we should consider renaming all the package constructor methods from: `mfpackages.dis_from_model_ds` to just `dis` etc. 

Also we're going to be getting some similar names from the Gwt model, which I think means we should rename mfpackages to `gwfpackages` or even just `gwf` and add a `gwt` or `gwtpackages` submodule for all transport related mf6 package building.

**Comment by OnnoEbbens** [comment]
I just made a pull request, #85, to add modpath, this also includes another structures for the `mfpackages`. I have not renamed `dis_from_model_ds` to `dis` because it may be hard if variables have the same names as functions. For example if we rename `gwf_from_model_ds` to `gwf` how are we going to call the `gwf` variable? I do think `gwf_from_model_ds` is too long so we should find something else.

**Comment by OnnoEbbens** [comment]
some ideas: 
1. `dis_from_ds` 
2. `get_dis`
3. `add_dis` because you add the dis to the gwf
4. `create_dis`

**Comment by rubencalje** [comment]
I would go for dis_from_ds

**Comment by dbrakenhoff** [comment]
Or renaming any internal references with name `dis` to something else :angel: ?

Because this is fine right?
```python
dis = nlmod.gwf.dis(ds)
```
