### ISSUE TITLE
start_steady_perlen gets value from cached get_northsea

### ISSUE THREAD

**Issue by bdestombe** [ArtesiaWater/nlmod#75]
https://github.com/ArtesiaWater/nlmod/blob/ce8479333b580652150e32f006fbb5823f7944ea/nlmod/mdims/mlayers.py#L930

The refered line also updates the time dimension and her attributes when loading from cache. These attributes are later used to set the tdis package.

The behavior I expect is that only the northsea variable is added from cache to model_ds, the icell2d coordinates are checked with the ones of model_ds, and the other data of model_ds is left untouched.

**Comment by bdestombe** [comment]
I just found out this is not specific to the adding the north sea function, but also others. I presume the solution would be found in the cache function, such that it only restores the data_vars

**Comment by OnnoEbbens** [comment]
Nice catch. The two options you suggest can both work:
1. Change the `model_ds.update` in such a way that only the data variables of the cached dataset are added to the model_ds not the attributes of the coordinates.
2. Modify the cache function. Add an extra check in `_check_ds` to see if the attributes of the coordinates of the cached dataset are the same as the model_ds.

The advantage of the first option is that you can use the cache even if you've changed the attributes of your coordinates. However, I think the 2nd option is much cleaner and less prone to errors. 

I've created a pull request for the 2nd option. Can you check it?

**Comment by bdestombe** [comment]
Hi Onno,
Why would you want to cache more than only the data_vars? You don't even need to cache the coordinates? Isn't all those data stored in the pickle file?

**Comment by OnnoEbbens** [comment]
Currently we don't store any information (values nor coördinates) of an xarray Dataset in the pickled file. If one of the function arguments is an xarray Dataset it is not saved in the pickle. We only check if the xarray dataset has the same coördinates as the cached Dataset (the netcdf file). I also tried to explain this in the notebook about [caching](https://github.com/ArtesiaWater/nlmod/blob/main/examples/05_caching.ipynb) but I can understand if that one is hard to read.

There are few reasons I decided to cache a Dataset and not a DataArray (data_vars):
1. There are several functions that produce multiple DataArrays, for example `nlmod.read.get_regis`. 
2. It is easy to write a Dataset to a netcdf file and it is fast when you read it again because some sort of lazy loading is implemented in xarray. This could probably be done with DataArrays as well but I don't know how.

**Comment by bdestombe** [comment]
Hi Onno,
Thanks for the explaination.

I understand that you'd want to use a Dataset where you save different DataArray and their dimensions in a netCDF file, but the coordinates don't need to be stored, right? 

That was my initial point of view. In hind sight, it may be better to also store and not reload the coordinates in the netCDF file, like you propose to do in the pull request. It could be useful for when you want to inspect individual cached netCDF files.

Cheers,
Bas
